name: Moodle Plugin CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  moodle-plugin-ci:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11.4
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        include:
          - moodle-branch: "MOODLE_404_STABLE"
            php: "8.2"
          - moodle-branch: "MOODLE_405_STABLE"
            php: "8.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: plugin
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, pdo_mysql, gd, xml, zip, curl, intl, soap
          ini-values: max_input_vars=5000
          coverage: none

      - name: Setup moodle-plugin-ci
        run: |
          git config --global url."https://github.com/".insteadOf "git://github.com/"
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$GITHUB_WORKSPACE/ci/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/ci/vendor/bin" >> $GITHUB_PATH

      - name: Install Moodle CI environment
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-type mariadb --db-host 127.0.0.1 --db-user root --branch ${{ github.ref_name }} --moodle ${{ matrix.moodle-branch }}

      - name: Run PHP lint check
        run: moodle-plugin-ci phplint

      - name: Run CodeSniffer
        working-directory: ./plugin
        run: >-
          phpcs --standard=moodle
          --exclude="moodle.Commenting.InlineComment,moodle.Files.LineLength,moodle.Files.LangFilesOrdering,moodle.Files.MoodleInternal,Squiz.PHP.CommentedOutCode" .

      - name: Run PHPMD
        run: moodle-plugin-ci phpmd

      - name: Run Moodle code checker
        run: moodle-plugin-ci validate
